In [84]:
import numpy as np
import matplotlib.pyplot as plt
import xarray as xr

## 3J PV

In [200]:
ts = xr.open_dataset('redsun_timeseries_17_00.nc')
bg1f = ts['j3-bg1']
bg2f = ts['j3-bg2']
bg3f = ts['j3-bg3']

ds = xr.open_dataset('j3PV.nc')
x,y = np.shape(ds['j3pv-bg1'])
latf = ds['lat']
lonf = ds['lon']

j3pvi_bg1 = np.zeros((37,19))
j3pvi_bg2 = np.zeros((37,19))
j3pvi_bg3 = np.zeros((37,19))

for i in range(0,x):
    for j in range(0,y):
        ind = np.array(ds['j3pv-bg1'][i][j])
        try:
            j3pvi_bg1[i][j] = np.float(bg1f[int(ind)])
        except:
            pass

x,y = np.shape(ds['j3pv-bg2'])
for i in range(0,x):
    for j in range(0,y):
        ind = np.array(ds['j3pv-bg2'][i][j])
        try:
            j3pvi_bg2[i][j] = np.float(bg2f[int(ind)])
        except:
            pass

x,y = np.shape(ds['j3pv-bg3'])        
for i in range(0,x):
    for j in range(0,y):
        ind = np.array(ds['j3pv-bg3'][i][j])
        try:
            j3pvi_bg3[i][j] = np.float(bg3f[int(ind)])
        except:
            pass

lats = np.arange(-90,91,10)
lons = np.arange(-180,181,10)
j3pvF = ds['j3pv']

test = xr.Dataset({'j3pv': (('lon','lat'), np.array(j3pvF)),
                            'j3pv-bg1': (('lon','lat'), j3pvi_bg1),
                            'j3pv-bg2': (('lon','lat'), j3pvi_bg2),
                            'j3pv-bg3': (('lon','lat'), j3pvi_bg3)},
                            coords = {
                                'lon': lons,
                                'lat': lats,
                            },)

test['lat'].attrs['units'] = 'degrees_north'
test['lon'].attrs['units'] = 'degrees_east'
test['j3pv'].attrs['units'] = '(kW*hr)/(day*m^2)'
test['j3pv-bg1'].attrs['units'] = 'eV'
test['j3pv-bg2'].attrs['units'] = 'eV'
test['j3pv-bg3'].attrs['units'] = 'eV'

test['j3pv'] = test['j3pv'].where(test['j3pv'] != 0.0)
test['j3pv-bg1'] = test['j3pv-bg1'].where(test['j3pv-bg1'] != 0.0)
test['j3pv-bg2'] = test['j3pv-bg2'].where(test['j3pv-bg2'] != 0.0)
test['j3pv-bg3'] = test['j3pv-bg3'].where(test['j3pv-bg3'] != 0.0)

test.to_netcdf('j3pv2.nc')


## 2JH2

In [202]:
ts = xr.open_dataset('redsun_timeseries_17_00.nc')
bg1f = ts['j2-bg1']
bg2f = ts['j2-bg2']
# bg3f = ts['j3-bg3']

ds = xr.open_dataset('j2h2.nc')
x,y = np.shape(ds['j2h2-bg1'])
latf = ds['lat']
lonf = ds['lon']

j2h2i_bg1 = np.zeros((37,19))
j2h2i_bg2 = np.zeros((37,19))
# j2h2i_bg3 = np.zeros((37,19))

for i in range(0,x):
    for j in range(0,y):
        ind = np.array(ds['j2h2-bg1'][i][j])
        try:
            j2h2i_bg1[i][j] = np.float(bg1f[int(ind)])
        except:
            pass

x,y = np.shape(ds['j2h2-bg2'])
for i in range(0,x):
    for j in range(0,y):
        ind = np.array(ds['j2h2-bg2'][i][j])
        try:
            j2h2i_bg2[i][j] = np.float(bg2f[int(ind)])
        except:
            pass

# x,y = np.shape(ds['j2h2-bg3'])        
# for i in range(0,x):
#     for j in range(0,y):
#         ind = np.array(ds['j2h2-bg3'][i][j])
#         try:
#             j2h2i_bg3[i][j] = np.float(bg3f[int(ind)])
#         except:
#             pass

lats = np.arange(-90,91,10)
lons = np.arange(-180,181,10)
j2h2F = ds['j2h2']

test = xr.Dataset({'j2h2': (('lon','lat'), np.array(j2h2F)),
                            'j2h2-bg1': (('lon','lat'), j2h2i_bg1),
                            'j2h2-bg2': (('lon','lat'), j2h2i_bg2)},
                            coords = {
                                'lon': lons,
                                'lat': lats,
                            },)

test['lat'].attrs['units'] = 'degrees_north'
test['lon'].attrs['units'] = 'degrees_east'
test['j2h2'].attrs['units'] = 'g/(day*m^2)'
test['j2h2-bg1'].attrs['units'] = 'eV'
test['j2h2-bg2'].attrs['units'] = 'eV'

test['j2h2'] = test['j2h2'].where(test['j2h2'] != 0.0)
test['j2h2-bg1'] = test['j2h2-bg1'].where(test['j2h2-bg1'] != 0.0)
test['j2h2-bg2'] = test['j2h2-bg2'].where(test['j2h2-bg2'] != 0.0)

test.to_netcdf('j2h22.nc')


In [164]:
latf

<xarray.DataArray 'lat' (lat: 19)>
array([-90, -80, -70, -60, -50, -40, -30, -20, -10,   0,  10,  20,  30,  40,
        50,  60,  70,  80,  90])
Coordinates:
  * lat      (lat) int64 -90 -80 -70 -60 -50 -40 -30 ... 30 40 50 60 70 80 90
Attributes:
    units:    degrees_north

In [163]:
latf

<xarray.DataArray 'j3pv-bg3' ()>
array(32.)
Coordinates:
    lon      int64 180
    lat      int64 90
Attributes:
    units:    eV

In [120]:
rep

<xarray.DataArray ()>
array(0.72)
Coordinates:
    lat      int64 19
    lon      int64 37

In [110]:
np.array(ds['lon'])

array([-180, -170, -160, -150, -140, -130, -120, -110, -100,  -90,  -80,
        -70,  -60,  -50,  -40,  -30,  -20,  -10,    0,   10,   20,   30,
         40,   50,   60,   70,   80,   90,  100,  110,  120,  130,  140,
        150,  160,  170,  180])

In [62]:
ds['j3pv-bg1']

<xarray.DataArray 'j3pv-bg1' (lon: 37, lat: 19)>
array([[ nan, 1.51, 1.51, ..., 1.51, 1.51, 1.51],
       [ nan, 1.51, 1.51, ..., 1.51, 1.51, 1.51],
       [ nan, 1.51, 1.51, ..., 1.51, 1.51, 1.51],
       ...,
       [1.51, 1.51, 1.51, ..., 1.51, 1.51, 1.51],
       [1.51, 1.51, 1.51, ..., 1.51, 1.51, 1.51],
       [1.51, 1.51, 1.51, ..., 1.51, 1.51, 1.51]])
Coordinates:
  * lon      (lon) int64 -180 -170 -160 -150 -140 -130 ... 140 150 160 170 180
  * lat      (lat) int64 -90 -80 -70 -60 -50 -40 -30 ... 30 40 50 60 70 80 90
Attributes:
    units:    eV

In [58]:
ds['j3pv-bg3'][i][j].

<xarray.DataArray 'j3pv-bg3' ()>
array(32.)
Coordinates:
    lon      int64 180
    lat      int64 90
Attributes:
    units:    eV